<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
      <PackageReference Include="CsvHelper" Version="33.1.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
      <PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.7" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\src\DotNetCommons.Services\DotNetCommons.Services.csproj" />
      <ProjectReference Include="..\src\DotNetCommons.SqlData\DotNetCommons.SqlData.csproj" />
      <ProjectReference Include="..\src\DotNetCommons\DotNetCommons.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="appsettings.json" />
      <Content Include="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
